---
language: node_js
node_js:
  - "lts/boron"

sudo: false

cache:
  directories:
    - node_modules

env:
  matrix:
    - TEST_DIR="exp-models"
    - TEST_DIR="exp-player"

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - npm config set spin false
  - npm install -g bower

install:
  - cd $TEST_DIR
  - npm link
  - npm install
  - bower install

script:
  - pwd
  - npm run check-style && npm test
